{{- $chartName := include "job-syncer.name" . -}}
{{- $fullName := include "job-syncer.fullname" . -}}
{{- $ca := (include "merged.ca" . ) | fromYaml }}
{{- $tracing := (include "merged.tracing" . ) | fromYaml }}
{{- $metrics := (include "merged.metrics" . ) | fromYaml }}
{{- $jobManager := (include "merged.jobManager" . ) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if $tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracing.url }}
  {{ end }}
  {{ if $metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metrics.url }}
  {{ end }}
  {{- if $ca.enabled }}
  REQUESTS_CA_BUNDLE: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  NODE_EXTRA_CA_CERTS: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  {{- end }}
  JOB_SYNCER_INTERVAL_MS: {{ .Values.env.intervalMS | quote }}
  CATALOG_URL: {{ .Values.env.catalog.url | default (printf "http://%s-catalog" .Release.Name) }}
  LINK_NAME: {{ .Values.env.catalog.link.name | quote }}
  LINK_DESCRIPTION: {{ .Values.env.catalog.link.description | quote }}
  LINK_URL: {{ .Values.env.catalog.link.url | quote }}
  LINK_PROTOCOL: {{ .Values.env.catalog.link.protocol | quote }}
  JOB_MANAGER_URL: {{ $jobManager.url | quote }}
  JOB_INGESTION_TYPE: {{ $jobManager.ingestion.jobType | quote }}
  JOB_DELETE_TYPE: {{ $jobManager.delete.jobType | quote }}
  SERVER_PORT: {{ .Values.env.targetPort | quote }}
