{
 "title": "Job Syncer",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jobs_duration_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{namespace=\"$namespace\",service_name=\"job-syncer\"}[$interval]) * 100",
     "legendFormat": "User CPU - {{pod}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{namespace=~\"$namespace\",service_name=\"job-syncer\"}[$interval]) * 100",
     "legendFormat": "Sys CPU - {{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=\"$namespace\",service_name=\"job-syncer\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Service State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\", service_name=\"job-syncer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{namespace=\"$namespace\",service_name=\"job-syncer\"}[$interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\",service_name=\"job-syncer\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=\"$namespace\",service_name=\"job-syncer\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=\"$namespace\",service_name=\"job-syncer\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{namespace=\"$namespace\",service_name=\"job-syncer\"}",
     "legendFormat": "External Memory - {{pod}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{namespace=\"$namespace\",service_name=\"job-syncer\"}",
     "legendFormat": "Active Handler - {{pod}}"
    },
    {
     "expr": "nodejs_active_requests_total{namespace=\"$namespace\",service_name=\"job-syncer\"}",
     "legendFormat": "Active Request - {{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Counts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_count{namespace=\"$namespace\",service_name=\"job-syncer\",kind=\"minor\"}[$interval])",
       "legendFormat": "minor : {{pod}}"
      },
      {
       "expr": "rate(nodejs_gc_duration_seconds_count{namespace=\"$namespace\",service_name=\"job-syncer\",kind=\"incremental\"}[$interval])",
       "legendFormat": "incremental : {{pod}}"
      },
      {
       "expr": "rate(nodejs_gc_duration_seconds_count{namespace=\"$namespace\",service_name=\"job-syncer\",kind=\"major\"}[$interval])",
       "legendFormat": "major : {{pod}}"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_duration_seconds_sum{namespace=\"$namespace\",service_name=\"job-syncer\",kind=\"minor\"}[$interval])",
       "legendFormat": "minor : {{pod}}"
      },
      {
       "expr": "rate(nodejs_gc_duration_seconds_sum{namespace=\"$namespace\",service_name=\"job-syncer\",kind=\"incremental\"}[$interval])",
       "legendFormat": "incremental : {{pod}}"
      },
      {
       "expr": "rate(nodejs_gc_duration_seconds_sum{namespace=\"$namespace\",service_name=\"job-syncer\",kind=\"major\"}[$interval])",
       "legendFormat": "major : {{pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}