apiVersion: v2
name: job-syncer
description: A Helm chart for job-syncer service
type: application
version: 2.6.0
appVersion: 2.6.0
dependencies:
  - name: mc-labels-and-annotations
    version: 0.7.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    alias: mcLabelsAndAnnotations
